---
# Permit co-located instances for solitary minikube virtual machines.
antiAffinity: "soft"

imageTag: "7.6.0"

# Shrink default JVM heap.
esJavaOpts: "-Xmx128m -Xms128m"

replicas: 3
minimumMasterNodes: 1

# Allocate smaller chunks of memory per pod.
resources:
  requests:
    cpu: "100m"
    memory: "512M"
  limits:
    cpu: "500m"
    memory: "512M"

# Request smaller persistent volumes.
volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "standard"
  resources:
    requests:
      storage: 1G
